### ISSUE TITLE
在iOS11系统上点击第三方（微信、QQ、支付宝等）的按钮好像都不弹出来分享界面

### ISSUE THREAD

**Issue by hpzerozero** [liugangios/IFMShare#7]
在iOS11系统上点击第三方（微信、QQ、支付宝等）的按钮好像都不弹出来分享界面，是不是iOS11的系统，腾讯和阿里那边还没适配？

**Comment by letu81** [comment]
+1，系统升级到ios 11.0.3h后，分享界面无法弹出了

**Comment by BeiXiao** [comment]
iOS11 上面Social 框架被去掉了，不能通过系统方法直接分享了

**Comment by zhangkun0625** [comment]
iOS11的不能用了
